package StockReader;

import java.net.URLEncoder;
import javax.swing.JOptionPane;

public class CSVOptionsGUI extends javax.swing.JFrame {

    SQLHelper sql = new SQLHelper();
    CSVDownloader csvd = new CSVDownloader();
    CSVParser csvp = new CSVParser();
    StockReader sr = new StockReader();

    public CSVOptionsGUI() {
        initComponents();
        sql.populateTable(tbl_csvo, sql.selectTracker(), "tracker"); //then populate table. 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jCheckBox1 = new javax.swing.JCheckBox();
        btn_csvo_updateall = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tf_csvo_stocksymbol = new javax.swing.JTextField();
        btn_csvo_downloadcsvs = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btn_csvo_uploadcsvs = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_csvo = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        btn_updateallstocks = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        btn_csvo_delete = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jButton2.setText("jButton2");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CSV Options");

        jLabel1.setText("Download CSV for:");

        tf_csvo_stocksymbol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_csvo_stocksymbolActionPerformed(evt);
            }
        });

        btn_csvo_downloadcsvs.setText("Download");
        btn_csvo_downloadcsvs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_csvo_downloadcsvsActionPerformed(evt);
            }
        });

        jLabel2.setText("CSVs to upload into database:");

        btn_csvo_uploadcsvs.setText("Select CSVs...");
        btn_csvo_uploadcsvs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_csvo_uploadcsvsActionPerformed(evt);
            }
        });

        tbl_csvo.setAutoCreateRowSorter(true);
        tbl_csvo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Stocks in Database", "Earliest Record", "Last Record"
            }
        ));
        jScrollPane2.setViewportView(tbl_csvo);

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("(Multiple CSVs can be selected by Shift+clicking each additional file. Downloaded CSVs will be stored in the same directory as this program.)");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setCursor(null);
        jTextArea1.setFocusable(false);
        jTextArea1.setMaximumSize(new java.awt.Dimension(2147483647, 44));
        jTextArea1.setMinimumSize(new java.awt.Dimension(5, 44));
        jScrollPane3.setViewportView(jTextArea1);

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setText("(Check the table to the right to see if the stock symbol already exists for the desired time period.)");
        jTextArea2.setWrapStyleWord(true);
        jTextArea2.setCursor(null);
        jTextArea2.setFocusable(false);
        jTextArea2.setMaximumSize(new java.awt.Dimension(2147483647, 40));
        jTextArea2.setMinimumSize(new java.awt.Dimension(5, 40));
        jScrollPane4.setViewportView(jTextArea2);

        btn_updateallstocks.setText("Update all stocks...");
        btn_updateallstocks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateallstocksActionPerformed(evt);
            }
        });

        btn_csvo_delete.setText("Delete...");
        btn_csvo_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_csvo_deleteActionPerformed(evt);
            }
        });

        jScrollPane6.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane6.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea4.setEditable(false);
        jTextArea4.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        jTextArea4.setColumns(20);
        jTextArea4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextArea4.setLineWrap(true);
        jTextArea4.setRows(5);
        jTextArea4.setText("(Delete data by selecting the row of the stock you want to delete and then click the \"Delete\" button.)");
        jTextArea4.setWrapStyleWord(true);
        jTextArea4.setCursor(null);
        jTextArea4.setFocusable(false);
        jTextArea4.setMaximumSize(new java.awt.Dimension(2147483647, 40));
        jTextArea4.setMinimumSize(new java.awt.Dimension(5, 40));
        jScrollPane6.setViewportView(jTextArea4);

        jLabel3.setText("Select a stock to remove, then click Delete:");

        jScrollPane7.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane7.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea5.setEditable(false);
        jTextArea5.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        jTextArea5.setColumns(20);
        jTextArea5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextArea5.setLineWrap(true);
        jTextArea5.setRows(5);
        jTextArea5.setText("(WARNING: This may take some time depending on how many stocks need to be updated.)");
        jTextArea5.setWrapStyleWord(true);
        jTextArea5.setCursor(null);
        jTextArea5.setFocusable(false);
        jTextArea5.setMaximumSize(new java.awt.Dimension(2147483647, 40));
        jTextArea5.setMinimumSize(new java.awt.Dimension(5, 40));
        jScrollPane7.setViewportView(jTextArea5);

        javax.swing.GroupLayout btn_csvo_updateallLayout = new javax.swing.GroupLayout(btn_csvo_updateall);
        btn_csvo_updateall.setLayout(btn_csvo_updateallLayout);
        btn_csvo_updateallLayout.setHorizontalGroup(
            btn_csvo_updateallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_csvo_updateallLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btn_csvo_updateallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3)
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_csvo_updateallLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_csvo_stocksymbol, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_csvo_downloadcsvs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane6)
                    .addComponent(btn_updateallstocks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane7)
                    .addComponent(jSeparator4)
                    .addGroup(btn_csvo_updateallLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_csvo_delete, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE))
                    .addGroup(btn_csvo_updateallLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_csvo_uploadcsvs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        btn_csvo_updateallLayout.setVerticalGroup(
            btn_csvo_updateallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_csvo_updateallLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btn_csvo_updateallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
                    .addGroup(btn_csvo_updateallLayout.createSequentialGroup()
                        .addGroup(btn_csvo_updateallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tf_csvo_stocksymbol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_csvo_downloadcsvs))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(btn_csvo_updateallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(btn_csvo_uploadcsvs))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(btn_csvo_updateallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(btn_csvo_delete))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_updateallstocks)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jMenu1.setText("File");

        jMenuItem1.setText("Close window");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_csvo_updateall, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_csvo_updateall, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_csvo_stocksymbolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_csvo_stocksymbolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_csvo_stocksymbolActionPerformed

    private void btn_csvo_downloadcsvsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_csvo_downloadcsvsActionPerformed
        setCursor(WAIT_CURSOR);
        if (tf_csvo_stocksymbol.getText().equalsIgnoreCase("") || tf_csvo_stocksymbol == null) {
            JOptionPane.showMessageDialog(null, "Unable to download as the Stock Symbol has not been supplied. Examples: 'AAPL' or '^DJI'. \nIf you are unsure of the stock symbol that the company uses, you can visit the Yahoo or Google finance pages and enter the name of the company. \nThe symbol should appear on the page next to the name.");
        } else {
            String[] stock = {URLEncoder.encode(tf_csvo_stocksymbol.getText().toUpperCase())};
            CSVDownloader csvd = new CSVDownloader(stock);
        }
        setCursor(null);
    }//GEN-LAST:event_btn_csvo_downloadcsvsActionPerformed

    private void btn_csvo_uploadcsvsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_csvo_uploadcsvsActionPerformed
        setCursor(WAIT_CURSOR);
        csvp.locateCSVs();
        sql.updateAllTrackerDates();
        sql.populateTable(tbl_csvo, sql.selectTracker(), "tracker");
        sql.populateTable(StockReaderGUI.tbl_gui, sql.selectLatestStocks(), "stock");
        setCursor(null);
        int tabCount = StockReaderGUI.main_panel.getTabCount() - 1;
        for (int i = tabCount; i > 0; i--) {
            StockReaderGUI.main_panel.removeTabAt(i);
        }
        sr = new StockReader();
        sr.getDataFromSQL();
        sr.createTabsDisplayCharts(null);
    }//GEN-LAST:event_btn_csvo_uploadcsvsActionPerformed

    private void btn_updateallstocksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateallstocksActionPerformed
        setCursor(WAIT_CURSOR);
        csvp.convertDirectoryToStock(csvd.updateAllCSVs());
        sql.populateTable(tbl_csvo, sql.selectTracker(), "tracker");
        sql.populateTable(StockReaderGUI.tbl_gui, sql.selectLatestStocks(), "stock");
        setCursor(null);
    }//GEN-LAST:event_btn_updateallstocksActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btn_csvo_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_csvo_deleteActionPerformed
        setCursor(WAIT_CURSOR);
        String stockSymbol = (String) tbl_csvo.getModel().getValueAt(tbl_csvo.getSelectedRow(), 0);
        if (stockSymbol.contains("^")) {
            stockSymbol = stockSymbol.replace("^", "");
        }
        sql.deleteStock(stockSymbol);
        sql.deleteTracker(stockSymbol);
        sql.populateTable(CSVOptionsGUI.tbl_csvo, sql.selectTracker(), "tracker");
        sql.populateTable(StockReaderGUI.tbl_gui, sql.selectLatestStocks(), "stock");
        setCursor(null);
    }//GEN-LAST:event_btn_csvo_deleteActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CSVOptionsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CSVOptionsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CSVOptionsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CSVOptionsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CSVOptionsGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_csvo_delete;
    private javax.swing.JButton btn_csvo_downloadcsvs;
    private javax.swing.JPanel btn_csvo_updateall;
    private javax.swing.JButton btn_csvo_uploadcsvs;
    private javax.swing.JButton btn_updateallstocks;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    public static javax.swing.JTable tbl_csvo;
    private javax.swing.JTextField tf_csvo_stocksymbol;
    // End of variables declaration//GEN-END:variables
}
